version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - pip3 install pipenv
      - pip3 install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pipenv install --skip-lock --dev
      - gdal-config --version
      - export CPLUS_INCLUDE_PATH=/usr/include/gdal
      - export C_INCLUDE_PATH=/usr/include/gdal
      - pip install pygdal==3.1.3.6


  build:
    commands:
      - echo Build started on `date`
      - pytest -v --cov-report term-missing --cov=src --cov=scripts
  post_build:
    commands:
      - echo Build completed on `date`
