version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - pip3 install pipenv
      - pip3 install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pipenv install --skip-lock --dev
      - gdal-config --version
      - pip install GDAL==3.2.0 --global-option=build_ext --global-option="-I/usr/include/gdal"


  build:
    commands:
      - echo Build started on `date`
      - pytest -v --cov-report term-missing --cov=src --cov=scripts
  post_build:
    commands:
      - echo Build completed on `date`
